name: pdf_download
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  persistent_bottom_nav_bar_v2: ^4.2.8
  text_divider: ^1.0.0
  file_picker: ^6.1.1
  awesome_dialog: ^3.2.0
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  firebase_core: ^2.25.4
  dio: ^5.4.0
  skeletons: ^0.0.3
  open_file: ^3.3.2
  badges: ^3.1.2
  path_provider: ^2.1.2
  flutter_native_splash: ^2.3.4
  flutter: 
    sdk: flutter
  firebase_auth: ^4.17.4

dev_dependencies: 
  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
flutter_native_splash:
  color: "#60a3d9"
  image: "assets/images/spinner-light.apng"
  color_dark: "#1c1b1f"
  image_dark: "assets/images/spinner-dark.apng"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/Icon-512.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/Icon-512.png"
