name: pdf_download
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  persistent_bottom_nav_bar_v2: ^4.2.8
  text_divider: ^1.0.0
  file_picker: ^6.1.1
  awesome_dialog: ^3.2.0
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  firebase_core: ^2.25.4
  dio: ^5.4.0
  skeletons: ^0.0.3
  open_file: ^3.3.2
  path_provider: ^2.1.2
  flutter: 
    sdk: flutter
  firebase_auth: ^4.17.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

