// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClqMPeRyFcwYyBlAUzwHJP-qsXXONzUoo',
    appId: '1:82192729153:web:e11f69fbf72fb88c1eb2c0',
    messagingSenderId: '82192729153',
    projectId: 'pdf-download-f7b98',
    authDomain: 'pdf-download-f7b98.firebaseapp.com',
    storageBucket: 'pdf-download-f7b98.appspot.com',
    measurementId: 'G-G4XH21E98N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfwrCvJqyQwqWOGd5pxh6q0vO_IjS9z2Y',
    appId: '1:82192729153:android:7944f41bd1b142431eb2c0',
    messagingSenderId: '82192729153',
    projectId: 'pdf-download-f7b98',
    storageBucket: 'pdf-download-f7b98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq-LJ5vLiyaN8onhW7w19s_YCc7v884wQ',
    appId: '1:82192729153:ios:5b3122ee61ab3a171eb2c0',
    messagingSenderId: '82192729153',
    projectId: 'pdf-download-f7b98',
    storageBucket: 'pdf-download-f7b98.appspot.com',
    iosBundleId: 'com.gdsc-ml.pdfDownload',
  );
}
